-- List all patients with their full names, gender, and date of birth.


SELECT 
    CONCAT(first_name, ' ', last_name) AS full_name,
    gender,
    date_of_birth
FROM
    patients;


-- Show all doctors along with their specialization and years of experience.

SELECT 
    first_name, last_name, specialization, years_experience
FROM
    doctors;


-- Display all upcoming appointments with patient name, doctor name, and appointment date.

SELECT 
    a.appointment_id,
    p.first_name AS patient_name,
    d.first_name AS doctor_name,
    a.appointment_date
FROM
    appointments AS a
        JOIN
    patients AS p ON a.patient_id = p.patient_id
        JOIN
    doctors AS d ON a.doctor_id = d.doctor_id;


-- List all treatments with their descriptions and cost.

SELECT DISTINCT
    treatment_type, description, cost
FROM
    treatment;

-- Find the total number of patients in the database.

SELECT 
    COUNT(patient_id) AS total_patient
FROM
    patients;
    
    
-- Show total appointments per doctor, ordered from most to least appointments.

SELECT 
    d.first_name AS doctor_name,
    COUNT(a.appointment_id) AS total_appointment
FROM
    appointments AS a
        JOIN
    doctors AS d ON a.doctor_id = d.doctor_id
GROUP BY doctor_name
ORDER BY total_appointment DESC; 


-- List all patients who have unpaid bills, including their bill amount and due date.

SELECT 
    b.patient_id,
    p.first_name as patient_name,
    b.amount,
    b.bill_date,
    b.payment_status
FROM
    billing AS b
        JOIN
    patients AS p ON b.patient_id = p.patient_id
WHERE
    payment_status != 'Paid';


-- Find the average cost of treatments for each specialization.

SELECT 
    d.specialization, AVG(t.cost) AS average_cost
FROM
    doctors AS d
        JOIN
    appointments AS a ON d.doctor_id = a.doctor_id
        JOIN
    treatment AS t ON t.appointment_id = a.appointment_id
GROUP BY d.specialization;


-- Get the most common treatment performed in the hospital.

SELECT 
    t.treatment_type,
    COUNT(DISTINCT p.patient_id) AS total_unique_patient
FROM
    treatment AS t
        JOIN
    appointments AS a ON a.appointment_id = t.appointment_id
        JOIN
    patients AS p ON p.patient_id = a.patient_id
GROUP BY t.treatment_type
ORDER BY total_unique_patient DESC
LIMIT 1;


-- Show the number of appointments per month for the current year.

SELECT 
    MONTHNAME(appointment_date) AS month_name, COUNT(appointment_id) as appointments
FROM
    appointments
GROUP BY month_name, MONTH(appointment_date)
ORDER BY MONTH(appointment_date);


-- Find patients who have taken more than one treatment.

SELECT 
    CONCAT(p.first_name, p.last_name) AS patient_name,
    p.patient_id,
    COUNT(a.patient_id) AS treatement_count
FROM
    appointments AS a
        JOIN
    patients AS p ON p.patient_id = a.patient_id
GROUP BY patient_id , patient_name;


-- Show each patient’s latest appointment date and the doctor they visited.


SELECT *
FROM (
    SELECT 
        p.patient_id, CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
        a.appointment_date,
        d.first_name AS doctor_name,
        DENSE_RANK() OVER(
            PARTITION BY p.patient_id
            ORDER BY a.appointment_date DESC
        ) AS ranking
    FROM patients AS p
    JOIN appointments AS a 
        ON p.patient_id = a.patient_id
    JOIN doctors AS d 
        ON d.doctor_id = a.doctor_id
) AS derived_table
WHERE ranking = 1;



-- Calculate the total revenue generated by the hospital from all billing records.

SELECT 
    d.hospital_branch, ROUND(SUM(b.amount), 2) AS total_revenue
FROM
    billing AS b
        JOIN
    appointments AS a ON a.patient_id = b.patient_id
        JOIN
    doctors AS d ON d.doctor_id = a.doctor_id
GROUP BY d.hospital_branch;


-- Show the top 3 highest-earning doctors based on total billed amount.

SELECT 
    d.doctor_id,
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
    ROUND(SUM(b.amount), 2) AS total_earning
FROM
    doctors AS d
        JOIN
    appointments AS a ON d.doctor_id = a.doctor_id
        JOIN
    billing AS b ON a.patient_id = b.patient_id
GROUP BY d.doctor_id , doctor_name
ORDER BY total_earning DESC
LIMIT 3;


-- Find patients who visited more than 3 different doctors.

SELECT 
    *
FROM
    (SELECT 
        p.patient_id,
            CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
            COUNT(DISTINCT d.doctor_id) AS doctors_count
    FROM
        patients AS p
    JOIN appointments AS a ON p.patient_id = a.patient_id
    JOIN doctors AS d ON a.doctor_id = d.doctor_id
    GROUP BY p.patient_id , patient_name) AS derived_table
WHERE
    doctors_count > 3;


-- Identify the busiest day of the week for appointments.

SELECT 
    DAYNAME(appointment_date) AS day_name,
    COUNT(appointment_id) AS appointments
FROM
    appointments
GROUP BY day_name
ORDER BY appointments DESC
LIMIT 1;


-- List all doctors along with their patient count and average treatment cost for those patients.

SELECT 
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
    COUNT(p.patient_id) AS patient_count,
    ROUND(AVG(t.cost), 2) AS average_treatment_cost
FROM
    doctors AS d
        JOIN
    appointments AS a ON d.doctor_id = a.doctor_id
        JOIN
    patients AS p ON a.patient_id = p.patient_id
        JOIN
    treatment AS t ON a.appointment_id = t.appointment_id
GROUP BY doctor_name;



-- Find the doctor-patient pair with the highest total billed amount.

SELECT 
    CONCAT(d.first_name,
            ' ',
            d.last_name,
            ' - ',
            p.first_name,
            ' ',
            p.last_name) AS doctor_patient,
    ROUND(SUM(b.amount),2) AS total_amount
FROM
    doctors AS d
        JOIN
    appointments AS a ON d.doctor_id = a.doctor_id
        JOIN
    patients AS p ON a.patient_id = p.patient_id
        JOIN
    billing AS b ON b.patient_id = p.patient_id
    GROUP BY doctor_patient
ORDER BY total_amount DESC
LIMIT 1;



-- Generate a running total of hospital revenue month-by-month using a window function.

SELECT month_name, SUM(revenue) OVER(ORDER BY month_number) AS running_total
 FROM
     (SELECT MONTH(appointment_date) AS month_number,
      monthname(a.appointment_date) AS month_name,
      SUM(b.amount) AS revenue
	  FROM billing AS b
		JOIN
	treatment AS t ON t.treatment_id = b.treatment_id
        JOIN
	appointments AS a ON a.appointment_id = t.appointment_id 
	GROUP BY month_name, MONTH(appointment_date)
ORDER BY MONTH(appointment_date)) AS derived_table
ORDER BY running_total;

